version: "3.7"
services:
  web:
    container_name: ${container_web}
    image: nginx:1.19
    ports:
      - "80:80" # default
      - "443:443"
    volumes:
      - "./log/nginx:/var/log/nginx"
      - "./config/nginx/nginxconfig:/etc/nginx/nginxconfig"
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/nginx/conf.d:/etc/nginx/conf.d"
      - "./config/php/adminer.php:/var/www/adminer/index.php"
      - "./config/certs:/etc/nginx/certs"
      - "./public:/var/www/public"
    depends_on:
      - php
    # restart: always
  php:
    container_name: ${container_app}
#    image: php:7.3-fpm
    user: "${UID}:${GID}"
    build:
      dockerfile: Dockerfile
      context: config/php
    volumes:
      - "./config/composer.phar:/usr/local/bin/composer"
      - "./config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./config/php/adminer.php:/var/www/adminer/index.php"
      - "./public:/var/www/public"
    depends_on:
      - mysql
    working_dir: /var/www/public
    # restart: always
  mysql:
    image: mariadb:10.4
    container_name: ${container_db}
    # restart: always
    env_file: .env
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    volumes:
      - "./config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./config/mysql:/etc/mysql/conf.d"
  redis:
    container_name: ${container_redis}
    image: redis:alpine
    env_file: .env
    # restart: always
    # ports:
    #   - "6379:6379"
  # varnish:
  #   image: varnish:stable
  #   container_name: varnish
  #   ports:
  #     - "8080:8080"
  es01:
    image: elasticsearch:7.10.1
    container_name: ${container_elasticsearch}
    environment:
      - discovery.type=single-node
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #    ports:
    #      - 9200:9200
    networks:
      - default
    # restart: always
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 8025:8025 # web ui
    networks:
      - default
    # restart: always

networks:
  default:
   name: development_network
